# adapted from: https://github.com/pypa/cibuildwheel/tree/main/examples
name: Release

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  build_wheels_and_sdist:
    name: Build wheels
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-20.04, macOS-11, windows-2019 ]
        python-version: [ '3.8' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel cibuildwheel==2.12.3
          pip install -r requirements-dev.txt

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse --config-file pyproject.toml

      - name: Build source distribution
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          python -m build --sdist
          mv dist/*.gz wheelhouse

      - name: Store the wheelhouse directory
        uses: actions/upload-artifact@v3
        with:
          name: wheels_and_sdist
          path: wheelhouse
          if-no-files-found: error

  upload_pypi:
    needs: [ build_wheels_and_sdist ]
    runs-on: ubuntu-20.04
    environment:
      name: pypi
      url: https://pypi.org/p/pyloras
    permissions:
      id-token: write
    steps:
      - name: Pull built wheels and sdist
        uses: actions/download-artifact@v3
        with:
          name: wheels_and_sdist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.5
        with:
          packages_dir: dist
